apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:    
        - --provider=oidc
        - --oidc-issuer-url=https://identity.mydomain.com/identity
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --client-id=joe.dev.client
        - --client-secret=Wq1APpZeqCP+WTrJPsZaH8012Zfd4/LbFN
        - --cookie-secret=sGBOr+eVZ2T
        - --redirect-url=https://test.toolsforsellers.com/
        - --email-domain=test.com
        # Register a new application
        # https://github.com/settings/applications/new

        image: quay.io/pusher/oauth2_proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy