apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  # TODO Needs to be dynamic based on Prod/Stage
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    # TODO Needs to be dynamic based on Prod/Stage
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: joseph.sprankle@aveva.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      # TODO Needs to be dynamic based on Prod/Stage                
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx